# Script to try out cilia beat frequency analysis in R
# Sam Siljee
# 19 February 2025

---
  title: "CBF analysis"
author: "Sam Siljee"
date: '2022-06-17'
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In this script I'm using the variable `d` to represent the donor/well, `x` for the pixel x coordinate, `y` for the pixel y coordinate, and `f` for the frame number.

```{r packages, include = FALSE}
library(dplyr) # Pipe and data manipulation
library(ggplot2) # plotting
library(signal) # Windowing for FFT
library(magick) # Read in video files, with `ffmpeg`
library(stringr) # Strip ".MOV" from file names
```

```{r Set some constants}
# Directories
input_dir <- "Input/"
output_dir <- "Output/"

# Set video details
height <- 360
width <- 640
frame_rate <- 480
num_frames <- 500
```

## Extract frames
```{r Extract frames}
# Vector for donor IDs - read from available .MOV files in input
donor_IDs <- list.files(input_dir) %>%
  grep(pattern = ".MOV$", value = TRUE) %>%
  str_remove(".MOV")

# Initialise a list to hold all pixel data
data_list <- list()

# Iterate over donors - extract relevant pixel values
for (d in donor_IDs) {
  # Print message to keep track of progress
  print(
    paste0(
      "Extracting frames for donor ",
      d,
      ", ",
      which(donor_IDs %in% d),
      " of ",
      length(donor_IDs)
    )
  )

  # Load video with magick
  video_frames <- image_read_video(paste0(input_dir, d, ".MOV"), fps = NULL)

  # keep the last X frames
  video_frames <- video_frames[(length(video_frames) - (num_frames - 1)):length(video_frames)]

  # Initialize an empty list to store grayscale frames
  frames_list <- vector("list", num_frames)

  # Extract pixel values and convert to greyscale
  for (f in 1:num_frames) {
    # Extract the current frame
    frame <- video_frames[f]

    # Convert the frame to grayscale
    frame_gray <- image_convert(frame, colorspace = "gray")

    # Get pixel values and scale to 0-255 range
    frame_matrix <- as.integer(image_data(frame_gray))

    # Store the frame as a matrix in the list
    frames_list[[f]] <- matrix(frame_matrix, ncol = width)
  }

  # Save the frame list under the relevant donor
  data_list[[d]] <- frames_list
  
  # Clear the cache to free space
  gc()
}

# Save the data as a .rda file
save(data_list, file = paste0(output_dir, "data_list.rda"))
```

## Signal power image
```{r Signal power image}
# A kind of signal power image:
# - Subtract each frame from the previous frame. (If you do this in R, be careful with signed/unsigned issues. If you have plenty of memory, convert all images to signed integer or to floating point).
# - Take the absolute value of those difference frames.
# - Add all the difference frames, resulting in a 360x640 image.

# Start loop through all donors
for (d in donor_IDs) {
  # Progress monitor
  print(
    paste0(
      "Maing signal power images for donor ",
      d,
      ", ",
      which(donor_IDs %in% d),
      " of ",
      length(donor_IDs)
    )
  )
  
  # Initialise blank matrix for signal power image
  signal_power_image <- matrix(data = NA, ncol = width, nrow = height)

  # Loop through pixels to get differences
  for (x in 1:height) { # loop through rows
    for (y in 1:width) { # Loop through columns

      # Initialise sum difference values
      sum_dif_vals <- 0

      for (f in 2:num_frames) { # loop through frames, skipping the first
        # Take absolute difference of one pixel value from the previous one
        difference <- abs(data_list[[d]][[f]][x, y] - data_list[[d]][[(f - 1)]][x, y])

        # Add to other difference values of the frame
        sum_dif_vals <- sum_dif_vals + difference
      }

      # Add sum difference values to signal power image
      signal_power_image[x, y] <- sum_dif_vals
    }
  }

  # Save as a PNG image - grayscale
  png(paste0(output_dir, "signal_power_image_", d, "_grayscale.png"), width = width, height = height)

  # Remove margins around the image
  par(mar = c(0, 0, 0, 0))

  image(signal_power_image, col = gray.colors(256), axes = FALSE, zlim = range(signal_power_image))

  dev.off()

  # Save as a PNG image - rainbow
  png(paste0(output_dir, "signal_power_image_", d, "_rainbow.png"), width = width, height = height)

  # Remove margins around the image
  par(mar = c(0, 0, 0, 0))

  image(signal_power_image, col = rainbow(256), axes = FALSE, zlim = range(signal_power_image))

  dev.off()
} # End loop through donors
```

## Variances
```{r Variances}
# Initialise list to contain variances
variance_list <- vector("list", length(donor_IDs))
names(variance_list) <- donor_IDs
for(d in donor_IDs) {
  variance_list[[d]] <- matrix(ncol = width, nrow = height)
}

for(d in donor_IDs) { # Loop through donors
  # Progress monitor
  print(
    paste0(
      "Calculating pixel variances for donor ",
      d,
      ", ",
      which(donor_IDs %in% d),
      " of ",
      length(donor_IDs)
    )
  )
  
  for (x in 1:height) { # loop through rows
    for (y in 1:width) { # Loop through columns
      # Initialise vector of pixel values
      pixel_values <- numeric()
      
      for(f in 1:num_frames) { # Loop through frames
        pixel_values <- c(pixel_values, data_list[[d]][[f]][x, y])
      }
      
      # Calculate variances and add to list in the required position
      variance_list[[d]][x, y] <- var(pixel_values)
    }
  }
}


# Save the data as a .rda file
save(variance_list, file = paste0(output_dir, "variance_list.rda"))

# Create variance images
for(d in donor_IDs) {
   # Progress monitor
  print(
    paste0(
      "Creating pixel variance images for donor ",
      d,
      ", ",
      which(donor_IDs %in% d),
      " of ",
      length(donor_IDs)
    )
  )
  
  # Save as a PNG image - grayscale
  png(paste0(output_dir, "variance_image_", d, "_grayscale.png"), width = width, height = height)
  
  # Remove margins around the image
  par(mar = c(0, 0, 0, 0))
  
  image(variance_list[[d]], col = gray.colors(256), axes = FALSE, zlim = range(variance_list[[d]]))
  
  dev.off()

   # Save as a PNG image - rainbow
  png(paste0(output_dir, "variance_image_", d, "_rainbow.png"), width = width, height = height)
  
  # Remove margins around the image
  par(mar = c(0, 0, 0, 0))
  
  image(variance_list[[d]], col = rainbow(256), axes = FALSE, zlim = range(variance_list[[d]]))
  
  dev.off()
}
```

## FFT dominant frequency
```{r FFT frequencies}
# Initialise list to contain variances
FFT_freq_list <- vector("list", length(donor_IDs))
names(FFT_freq_list) <- donor_IDs
for(d in donor_IDs) {
  FFT_freq_list[[d]] <- matrix(ncol = width, nrow = height)
}

for(d in donor_IDs) { # Loop through donors
  # Progress monitor
  print(
    paste0(
      "Calculating pixel variances for donor ",
      d,
      ", ",
      which(donor_IDs %in% d),
      " of ",
      length(donor_IDs)
    )
  )
  
  for (x in 1:height) { # loop through rows
    for (y in 1:width) { # Loop through columns
      # Initialise vector of pixel values
      pixel_values <- numeric()
      
      for(f in 1:num_frames) { # Loop through frames
        pixel_values <- c(pixel_values, data_list[[d]][[f]][x, y])
      }
      
      # Calculate the dominant frequency from pixel values
      # Run FFT
      fft_result <- fft(pixel_values)
      
      # Find maximum magnitude - using half the dataset (symetrical)
      magnitude <- abs(fft_result[1:(num_frames/2 + 1)])
      
      # Create frequency vector
      freq <- seq(0, frame_rate/2, length.out = num_frames/2 + 1)
      
      # Find the frequency with maximum amplitude
      # Excluding the DC component (first element)
      max_index <- which.max(magnitude[2:length(magnitude)]) + 1
      
      # Add to list in the required position
      FFT_freq_list[[d]][x, y] <- freq[max_index]
    }
  }
} 

# Save the data as a .rda file
save(FFT_freq_list, file = paste0(output_dir, "FFT_freq_list.rda"))

# Create dominant frequency images
for(d in donor_IDs) {
   # Progress monitor
  print(
    paste0(
      "Creating pixel FFT frequency image for donor ",
      d,
      ", ",
      which(donor_IDs %in% d),
      " of ",
      length(donor_IDs)
    )
  )
  
  # Save as a PNG image - grayscale
  png(paste0(output_dir, "FFT_freq_image_", d, "_grayscale.png"), width = width, height = height)
  
  # Remove margins around the image
  par(mar = c(0, 0, 0, 0))
  
  image(FFT_freq_list[[d]], col = gray.colors(256), axes = FALSE, zlim = range(FFT_freq_list[[d]]))
  
  dev.off()

   # Save as a PNG image - rainbow
  png(paste0(output_dir, "FFT_freq_image_", d, "_rainbow.png"), width = width, height = height)
  
  # Remove margins around the image
  par(mar = c(0, 0, 0, 0))
  
  image(FFT_freq_list[[d]], col = rainbow(256), axes = FALSE, zlim = range(FFT_freq_list[[d]]))
  
  dev.off()
}
```
